version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: auctionService
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - bidflow-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - bidflow-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      timeout: 10s
      retries: 5

  bidflow:
    image: ${DOCKER_USERNAME}/bidflow:${IMAGE_TAG:-latest}
    container_name: bidflow
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./config/application.yml:/app/config/application.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/app/config/"
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_REDIS_HOST: "redis-cache"
      SPRING_REDIS_PASSWORD: "${REDIS_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/auctionService?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    networks:
      - bidflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mysql_data:
  redis_data:

networks:
  bidflow-network:
    driver: bridge 