apiVersion: 1

# Grafana 데이터 소스 설정
# Prometheus를 데이터 소스로 등록하여 메트릭 데이터를 시각화할 수 있도록 설정

datasources:
  # Prometheus 데이터 소스 설정
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    # JSON 데이터 설정
    jsonData:
      # HTTP 메서드 설정 (POST 권장)
      httpMethod: POST
      # 알림 관리 활성화
      manageAlerts: true
      # Prometheus 타입 설정
      prometheusType: Prometheus
      # Prometheus 버전 설정
      prometheusVersion: 3.3.0
      # 캐시 레벨 설정 (높은 성능을 위해 High로 설정)
      cacheLevel: 'High'
      # 기록 규칙 타겟 허용
      allowAsRecordingRulesTarget: true
      # 시간 간격 설정 (10초)
      timeInterval: 10s
      # 증분 쿼리 중복 윈도우 설정
      incrementalQueryOverlapWindow: 10m
      # 예시 추적 ID 대상 설정 (선택사항)
      # exemplarTraceIdDestinations:
      #   - datasourceUid: my_jaeger_uid
      #     name: traceID
    # 편집 가능 여부
    editable: true
    # 읽기 전용 여부
    readOnly: false 